jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: DeterminateSystems/nix-installer-action@v16
    - name: Check flake
      run: nix -Lv flake check
    timeout-minutes: 15
'on':
  push: {}
  workflow_dispatch: {}
